In [1]:
# Import necessary libraries

import pandas as pd
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
# Read `new housing` data
housing = pd.read_csv("new.csv")

# Check fisrt five rows of `housing` data
housing.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,address
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,"Ecological Study Area, Smyth Road, Panoramic H..."
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,"Grizzly Peak Open Space, Fish Ranch Road, Oakl..."
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,"Grove Shafter Freeway, Upper Rockridge, Oaklan..."
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame..."
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame..."

In [ ]:
# Read `crime` data
crime = pd.read_csv("ca_offenses_by_city.csv")

# Check fisrt five rows of `housing` data
crime.head()

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
0,Adelanto,"33,005",212,2,14,NaN,48,148,808,434,254,120,24
1,Agoura Hills,"20,970",15,0,1,NaN,6,8,310,82,217,11,0
2,Alameda,"78,613",148,2,7,NaN,61,78,"1,819",228,"1,245",346,18
3,Albany,"19,723",34,1,6,NaN,16,11,605,95,447,63,0
4,Alhambra3,"86,175",168,1,13,NaN,74,80,"1,929",305,"1,413",211,6

In [ ]:
# Check `housing` data details
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          20640 non-null  int64
 1   longitude           20640 non-null  float64
 2   latitude            20640 non-null  float64
 3   housing_median_age  20640 non-null  float64
 4   total_rooms         20640 non-null  float64
 5   total_bedrooms      20433 non-null  float64
 6   population          20640 non-null  float64
 7   households          20640 non-null  float64
 8   median_income       20640 non-null  float64
 9   median_house_value  20640 non-null  float64
 10  ocean_proximity     20640 non-null  object
 11  address             20640 non-null  object
dtypes: float64(9), int64(1), object(2)
memory usage: 1.9+ MB

In [ ]:
# Check `crime` data details
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   City                                  460 non-null    object
 1   Population                            460 non-null    object
 2   Violent crime                         460 non-null    object
 3   Murder and nonnegligent manslaughter  460 non-null    int64
 4   Rape (revised definition)             460 non-null    object
 5   Rape (legacy definition)              0 non-null      float64
 6   Robbery                               460 non-null    object
 7   Aggravated assault                    460 non-null    object
 8   Property crime                        460 non-null    object
 9   Burglary                              460 non-null    object
 10  Larceny-theft                         460 non-null    object
 11  Motor vehicle theft                   460 non-null    object
 12  Arson                                 460 non-null    object
dtypes: float64(1), int64(1), object(11)
memory usage: 46.8+ KB

In [ ]:
# Check some individual data points in the `address` columns
housing['address'][1]

'Grizzly Peak Open Space, Fish Ranch Road, Oakland, Alameda County, California, 94563, United States'

In [ ]:
housing ['address'][7]

'5401, Bryant Avenue, Rockridge, North Oakland, Oakland, Alameda County, California, 94168, United States'

In [ ]:
housing ['address'][27]

'1404, 66th Street, Harmon Tract, Berkeley, Alameda County, California, 94703, United States'

In [ ]:
housing ['address'][50]

'Grove Shafter Freeway, Hoover-Foster, North Oakland, Oakland, Alameda County, California, 94609, United States'

In [ ]:
housing ['address'][17]

'1889;1891;1893;1895, Harmon Street, Lorin, Berkeley, Alameda County, California, 94705, United States'

In [ ]:
housing ['address'][9000]

'4664, Addington Way, View Park-Windsor Hills, Los Angeles County, California, 90043, United States'

### After checking the `location` column, the **cities** can be obtained from the negative *5th* object in the `location` column

In [ ]:
# Load `crime` data
#crime = pd.read_csv('/content/ca_offenses_by_city.csv')

#crime.head()

In [ ]:
# Split the `address` column to get the `city`.

housing['city'] = housing ['address'].str.split(',').str[-5].str.strip()

housing.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,address,city
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,"Ecological Study Area, Smyth Road, Panoramic H...",Berkeley
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,"Grizzly Peak Open Space, Fish Ranch Road, Oakl...",Oakland
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,"Grove Shafter Freeway, Upper Rockridge, Oaklan...",Oakland
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...",Oakland
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...",Oakland

In [ ]:
# Check which `cities` where sampled from the `housing` data.
housing['city'].unique()

array(['Berkeley', 'Oakland', 'Emeryville', ..., 'Indiana Ranch Road',
       'Vierra Road', 'Marysville Road'], dtype=object)

In [ ]:
# Group the data using the `city` column.
# This is important because the `crime` data is based on `cities`.
# `Mean` and `sum` were used for aggregation.
# Some columns such as `longitude` and `latitude` can be taken off.
grouped_data = housing.groupby('city').agg({
    'longitude': 'mean',
    'latitude': 'mean',
    'housing_median_age': 'mean',
    'total_rooms': 'sum',
    'total_bedrooms': 'sum',
    'population': 'sum',
    'households': 'sum',
    'median_income': 'mean',
    'median_house_value': 'mean'
}).reset_index()

grouped_data.head()

,city,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,(private),-120.69,35.28,26.0,4225.0,886.0,1795.0,704.0,2.2847,247000.0
1,100,-122.66,38.81,22.0,852.0,176.0,461.0,142.0,3.4375,83300.0
2,103 Trail (Farr Family Trail),-119.19,34.30,25.0,2197.0,320.0,934.0,330.0,6.3110,283200.0
3,107th Street West,-118.32,34.62,31.0,1398.0,273.0,884.0,299.0,4.8409,264900.0
4,112th Street East,-117.93,34.57,5.0,5613.0,1060.0,3569.0,999.0,3.1946,132700.0

In [ ]:
# Check unique cities from the `crime` data.
crime['City'].unique()

array(['Adelanto', 'Agoura Hills', 'Alameda', 'Albany', 'Alhambra3',
       'Aliso Viejo', 'Alturas3', 'American Canyon3', 'Anaheim3',
       'Anderson', 'Antioch', 'Apple Valley', 'Arcadia', 'Arcata3',
       'Arroyo Grande3', 'Artesia', 'Arvin', 'Atascadero3', 'Atherton',
       'Atwater', 'Auburn', 'Avalon', 'Avenal3', 'Azusa', 'Bakersfield',
       'Baldwin Park3', 'Banning', 'Barstow', 'Bear Valley3', 'Beaumont',
       'Bell', 'Bellflower', 'Bell Gardens3', 'Belmont', 'Belvedere',
       'Benicia', 'Berkeley', 'Beverly Hills3', 'Big Bear Lake', 'Biggs3',
       'Bishop3', 'Blythe', 'Bradbury', 'Brawley3', 'Brea3', 'Brentwood',
       'Brisbane', 'Broadmoor', 'Buellton3', 'Buena Park3', 'Burbank',
       'Burlingame', 'Calabasas', 'Calexico3', 'California City',
       'Calimesa', 'Calistoga', 'Camarillo', 'Campbell', 'Canyon Lake',
       'Capitola', 'Carlsbad', 'Carmel', 'Carpinteria', 'Carson',
       'Cathedral City', 'Central Marin', 'Ceres', 'Cerritos', 'Chico3',
       'Chino', 'Chino Hills', 'Chowchilla', 'Chula Vista',
       'Citrus Heights', 'City of Angels3', 'Claremont3', 'Clayton',
       'Clearlake3', 'Cloverdale', 'Clovis', 'Coachella', 'Coalinga',
       'Colma3', 'Colton', 'Colusa3', 'Commerce', 'Compton', 'Concord',
       'Corcoran3', 'Corning', 'Corona', 'Coronado', 'Costa Mesa3',
       'Cotati', 'Covina3', 'Crescent City3', 'Cudahy', 'Culver City',
       'Cupertino', 'Cypress3', 'Daly City', 'Dana Point', 'Danville',
       'Davis', 'Delano', 'Del Mar', 'Del Rey Oaks', 'Desert Hot Springs',
       'Diamond Bar', 'Dinuba3', 'Dixon', 'Dorris3', 'Dos Palos',
       'Downey3', 'Duarte', 'Dublin', 'Dunsmuir3', 'East Palo Alto3',
       'Eastvale', 'El Cajon', 'El Centro3', 'El Cerrito', 'Elk Grove',
       'El Monte3', 'El Segundo3', 'Emeryville3', 'Encinitas', 'Escalon',
       'Escondido', 'Etna3', 'Eureka3', 'Exeter3', 'Fairfax', 'Fairfield',
       'Farmersville', 'Ferndale3', 'Fillmore', 'Firebaugh', 'Folsom',
       'Fontana', 'Fort Bragg', 'Fort Jones3', 'Fortuna3', 'Foster City3',
       'Fountain Valley3', 'Fowler', 'Fremont', 'Fresno', 'Fullerton3',
       'Galt', 'Gardena3', 'Garden Grove3', 'Gilroy', 'Glendale3',
       'Glendora3', 'Goleta', 'Gonzales', 'Grand Terrace', 'Grass Valley',
       'Greenfield', 'Gridley3', 'Grover Beach3', 'Guadalupe', 'Gustine',
       'Hanford3', 'Hawaiian Gardens', 'Hawthorne3', 'Hayward',
       'Healdsburg3', 'Hemet', 'Hercules', 'Hermosa Beach3', 'Hesperia',
       'Hidden Hills', 'Highland', 'Hillsborough', 'Hollister',
       'Holtville3', 'Hughson3', 'Huntington Beach', 'Huntington Park',
       'Huron', 'Imperial3', 'Imperial Beach', 'Indian Wells', 'Indio',
       'Industry', 'Inglewood3', 'Ione', 'Irvine3', 'Irwindale3',
       'Isleton', 'Jackson3', 'Jurupa Valley', 'Kensington', 'Kerman',
       'King City', 'Kingsburg', 'La Canada Flintridge', 'Lafayette',
       'Laguna Beach3', 'Laguna Hills', 'Laguna Niguel', 'Laguna Woods3',
       'La Habra3', 'La Habra Heights', 'Lake Elsinore', 'Lake Forest',
       'Lakeport', 'Lake Shastina3', 'Lakewood', 'La Mesa', 'La Mirada',
       'Lancaster', 'La Palma3', 'La Puente', 'La Quinta', 'La Verne3',
       'Lawndale', 'Lemon Grove', 'Lemoore3', 'Lincoln', 'Lindsay3',
       'Livermore', 'Livingston', 'Lodi3', 'Loma Linda', 'Lomita',
       'Long Beach', 'Los Alamitos3', 'Los Altos', 'Los Altos Hills',
       'Los Angeles', 'Los Banos', 'Los Gatos', 'Lynwood', 'Madera',
       'Malibu', 'Mammoth Lakes', 'Manhattan Beach3', 'Manteca', 'Marina',
       'Martinez', 'Marysville', 'Maywood', 'McFarland', 'Menifee',
       'Mendota', 'Menlo Park3', 'Merced', 'Mill Valley', 'Milpitas',
       'Mission Viejo', 'Modesto', 'Monrovia', 'Montague3', 'Montclair',
       'Montebello3', 'Monterey', 'Monterey Park3', 'Monte Sereno',
       'Moorpark', 'Moraga', 'Moreno Valley', 'Morgan Hill3', 'Morro Bay',
       'Mountain View', 'Mount Shasta3', 'Murrieta', 'Napa',
       'National City', 'Needles', 'Nevada City3', 'Newark', 'Newman',
       'Newport Beach', 'Norco', 'Norwalk', 'Novato', 'Oakdale',
       'Oakland', 'Oakley', 'Oceanside', 'Ojai', 'Ontario', 'Orange3',
       'Orange Cove', 'Orinda', 'Orland3', 'Oroville3', 'Oxnard',
       'Pacifica', 'Pacific Grove', 'Palmdale', 'Palm Desert',
       'Palm Springs', 'Palo Alto3', 'Palos Verdes Estates', 'Paradise3',
       'Paramount', 'Parlier', 'Pasadena3', 'Paso Robles3', 'Patterson3',
       'Perris', 'Petaluma', 'Pico Rivera', 'Piedmont', 'Pinole',
       'Pismo Beach3', 'Pittsburg', 'Placentia3', 'Placerville3',
       'Pleasant Hill', 'Pleasanton', 'Pomona3', 'Porterville',
       'Port Hueneme', 'Poway', 'Rancho Cordova', 'Rancho Cucamonga',
       'Rancho Mirage', 'Rancho Palos Verdes', 'Rancho Santa Margarita',
       'Red Bluff', 'Redding', 'Redlands', 'Redondo Beach',
       'Redwood City', 'Reedley', 'Rialto', 'Ridgecrest', 'Rio Dell3',
       'Rio Vista', 'Ripon', 'Riverbank3', 'Riverside', 'Rocklin',
       'Rohnert Park', 'Rolling Hills', 'Rolling Hills Estates',
       'Rosemead', 'Roseville', 'Ross', 'Sacramento', 'Salinas',
       'San Bernardino', 'San Bruno', 'San Clemente', 'Sand City',
       'San Diego', 'San Dimas', 'San Fernando3', 'San Francisco',
       'San Gabriel3', 'Sanger', 'San Jacinto', 'San Jose',
       'San Juan Capistrano', 'San Leandro', 'San Luis Obispo',
       'San Marcos', 'San Marino3', 'San Mateo', 'San Pablo',
       'San Rafael', 'San Ramon', 'Santa Ana3', 'Santa Barbara3',
       'Santa Clara', 'Santa Clarita', 'Santa Cruz3', 'Santa Fe Springs3',
       'Santa Maria', 'Santa Monica', 'Santa Paula3', 'Santa Rosa3',
       'Santee', 'Saratoga', 'Sausalito', 'Scotts Valley3', 'Seal Beach3',
       'Seaside', 'Sebastopol3', 'Selma', 'Shafter', 'Sierra Madre',
       'Signal Hill', 'Simi Valley3', 'Solana Beach', 'Soledad',
       'Solvang', 'Sonoma3', 'Sonora3', 'South El Monte', 'South Gate3',
       'South Lake Tahoe3', 'South Pasadena3', 'South San Francisco',
       'Stallion Springs', 'Stanton', 'St. Helena', 'Stockton',
       'Suisun City', 'Sunnyvale', 'Susanville3', 'Sutter Creek3', 'Taft',
       'Tehachapi', 'Temecula', 'Temple City', 'Thousand Oaks',
       'Tiburon3', 'Torrance3', 'Tracy', 'Truckee', 'Tulare', 'Tulelake3',
       'Turlock3', 'Tustin3', 'Twentynine Palms', 'Ukiah', 'Union City',
       'Upland', 'Vacaville', 'Vallejo', 'Ventura', 'Vernon3',
       'Victorville', 'Villa Park', 'Visalia', 'Vista', 'Walnut',
       'Walnut Creek', 'Waterford3', 'Watsonville', 'Weed', 'West Covina',
       'West Hollywood', 'Westlake Village', 'Westminster',
       'Westmorland3', 'West Sacramento', 'Wheatland', 'Whittier3',
       'Wildomar', 'Williams3', 'Willits', 'Willows', 'Windsor',
       'Winters', 'Woodlake3', 'Woodland', 'Yorba Linda', 'Yountville3',
       'Yreka', 'Yuba City', 'Yucaipa', 'Yucca Valley'], dtype=object)

In [ ]:
# Remove the `3` that come with some of the cities
crime['City'] = crime['City'].str.replace('3', '')

crime['City'].nunique

<bound method IndexOpsMixin.nunique of 0          Adelanto
1      Agoura Hills
2           Alameda
3            Albany
4          Alhambra
           ...
455      Yountville
456           Yreka
457       Yuba City
458         Yucaipa
459    Yucca Valley
Name: City, Length: 460, dtype: object>

In [ ]:
# Check unique values of the `city` column from the `grouped_data`
# to confirm whether there are some of the values from it in the `crime` data
grouped_data['city'].unique()

array(['(private)', '100', '103 Trail (Farr Family Trail)', ...,
       'Zachary Avenue', 'Zelinda Drive', 'Zuckerman Court'], dtype=object)

In [ ]:
# Rename `City` from the `crime` data to `city`.
# This is needed so that the data can be merged using that column.
crime = crime.rename(columns = {'City': 'city'})

crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 13 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   city                                  460 non-null    object
 1   Population                            460 non-null    object
 2   Violent crime                         460 non-null    object
 3   Murder and nonnegligent manslaughter  460 non-null    int64
 4   Rape (revised definition)             460 non-null    object
 5   Rape (legacy definition)              0 non-null      float64
 6   Robbery                               460 non-null    object
 7   Aggravated assault                    460 non-null    object
 8   Property crime                        460 non-null    object
 9   Burglary                              460 non-null    object
 10  Larceny-theft                         460 non-null    object
 11  Motor vehicle theft                   460 non-null    object
 12  Arson                                 460 non-null    object
dtypes: float64(1), int64(1), object(11)
memory usage: 46.8+ KB

In [ ]:
# Merge data from `crime` and `grouped_data` on the `city` using `left` to maintain all data from both datasets.
merged_data = pd.merge(crime, grouped_data, on='city', how='left')

merged_data.head()

,city,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,...,Arson,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,Adelanto,"33,005",212,2,14,NaN,48,148,808,434,...,24,-117.413333,34.583333,10.666667,9268.0,2240.0,5614.0,2004.0,1.681733,66933.333333
1,Agoura Hills,"20,970",15,0,1,NaN,6,8,310,82,...,0,-118.785000,34.150000,8.000000,33408.0,4597.0,14016.0,4397.0,6.934250,449600.500000
2,Alameda,"78,613",148,2,7,NaN,61,78,"1,819",228,...,18,-122.255385,37.766154,45.057692,131786.0,25494.0,63137.0,25795.0,3.813152,247886.538462
3,Albany,"19,723",34,1,6,NaN,16,11,605,95,...,0,-122.298125,37.893750,42.750000,32001.0,7151.0,14683.0,6810.0,3.669300,220562.500000
4,Alhambra,"86,175",168,1,13,NaN,74,80,"1,929",305,...,6,-118.135833,34.083542,37.437500,117422.0,28248.0,81333.0,27308.0,3.206000,217750.000000

In [ ]:
merged_data.tail()

,city,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Rape (legacy definition),Robbery,Aggravated assault,Property crime,Burglary,...,Arson,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
455,Yountville,"3,030",7,0,0,NaN,0,7,46,7,...,0,-122.360000,38.405000,17.000000,4524.0,946.0,1866.0,870.0,2.980150,188100.000000
456,Yreka,"7,507",47,1,4,NaN,4,38,309,85,...,1,-122.636000,41.732000,29.800000,15337.0,3154.0,6913.0,3011.0,2.262380,65780.000000
457,Yuba City,"65,974",216,0,28,NaN,66,122,"1,792",429,...,14,-121.628667,39.136000,23.933333,75544.0,15072.0,38624.0,14441.0,2.884130,92993.333333
458,Yucaipa,"53,498",94,2,8,NaN,22,62,"1,309",263,...,12,-117.054211,34.027895,24.421053,67846.0,13307.0,30949.0,12464.0,3.034968,124742.105263
459,Yucca Valley,"21,672",151,0,8,NaN,30,113,664,217,...,8,-116.411429,34.120000,14.285714,32324.0,6418.0,13857.0,5763.0,2.718271,88557.142857

In [ ]:
# Confirm marging
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460 entries, 0 to 459
Data columns (total 22 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   city                                  460 non-null    object
 1   Population                            460 non-null    object
 2   Violent crime                         460 non-null    object
 3   Murder and nonnegligent manslaughter  460 non-null    int64
 4   Rape (revised definition)             460 non-null    object
 5   Rape (legacy definition)              0 non-null      float64
 6   Robbery                               460 non-null    object
 7   Aggravated assault                    460 non-null    object
 8   Property crime                        460 non-null    object
 9   Burglary                              460 non-null    object
 10  Larceny-theft                         460 non-null    object
 11  Motor vehicle theft                   460 non-null    object
 12  Arson                                 460 non-null    object
 13  longitude                             439 non-null    float64
 14  latitude                              439 non-null    float64
 15  housing_median_age                    439 non-null    float64
 16  total_rooms                           439 non-null    float64
 17  total_bedrooms                        439 non-null    float64
 18  population                            439 non-null    float64
 19  households                            439 non-null    float64
 20  median_income                         439 non-null    float64
 21  median_house_value                    439 non-null    float64
dtypes: float64(10), int64(1), object(11)
memory usage: 82.7+ KB

In [ ]:
# Drop some columns and `NaN`
merged_data = merged_data.drop('Rape (legacy definition)', axis = 1).dropna().reset_index(drop=True)

merged_data.head()

,city,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition),Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,...,Arson,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,Adelanto,"33,005",212,2,14,48,148,808,434,254,...,24,-117.413333,34.583333,10.666667,9268.0,2240.0,5614.0,2004.0,1.681733,66933.333333
1,Agoura Hills,"20,970",15,0,1,6,8,310,82,217,...,0,-118.785000,34.150000,8.000000,33408.0,4597.0,14016.0,4397.0,6.934250,449600.500000
2,Alameda,"78,613",148,2,7,61,78,"1,819",228,"1,245",...,18,-122.255385,37.766154,45.057692,131786.0,25494.0,63137.0,25795.0,3.813152,247886.538462
3,Albany,"19,723",34,1,6,16,11,605,95,447,...,0,-122.298125,37.893750,42.750000,32001.0,7151.0,14683.0,6810.0,3.669300,220562.500000
4,Alhambra,"86,175",168,1,13,74,80,"1,929",305,"1,413",...,6,-118.135833,34.083542,37.437500,117422.0,28248.0,81333.0,27308.0,3.206000,217750.000000

In [ ]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   city                                  439 non-null    object
 1   Population                            439 non-null    object
 2   Violent crime                         439 non-null    object
 3   Murder and nonnegligent manslaughter  439 non-null    int64
 4   Rape (revised definition)             439 non-null    object
 5   Robbery                               439 non-null    object
 6   Aggravated assault                    439 non-null    object
 7   Property crime                        439 non-null    object
 8   Burglary                              439 non-null    object
 9   Larceny-theft                         439 non-null    object
 10  Motor vehicle theft                   439 non-null    object
 11  Arson                                 439 non-null    object
 12  longitude                             439 non-null    float64
 13  latitude                              439 non-null    float64
 14  housing_median_age                    439 non-null    float64
 15  total_rooms                           439 non-null    float64
 16  total_bedrooms                        439 non-null    float64
 17  population                            439 non-null    float64
 18  households                            439 non-null    float64
 19  median_income                         439 non-null    float64
 20  median_house_value                    439 non-null    float64
dtypes: float64(9), int64(1), object(11)
memory usage: 72.1+ KB

In [ ]:
cols_to_rename = {
    'Population': 'population',
    'Violent crime': 'violent_crime',
    'Murder and nonnegligent manslaughter': 'murder',
    'Rape (revised definition)': 'rape_cases',
    'Robbery': 'robbery_crime',
    'Aggravated assault': 'assault_crime',
    'Property crime': 'property_crime',
    'Burglary': 'burglary_crime',
    'Larceny-theft': 'larceny_theft',
    'Motor vehicle theft': 'motor_vehicle_theft',
    'Arson': 'arson',
    'housing_median_age': 'average_housing_age',
    'households': 'total_households',
    'median_income': 'average_income',
    'median_house_value': 'average_house_value',
    'population': 'population_drop'
}

In [ ]:
merged_data = merged_data.rename(columns = cols_to_rename)

merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   city                 439 non-null    object
 1   population           439 non-null    object
 2   violent_crime        439 non-null    object
 3   murder               439 non-null    int64
 4   rape_cases           439 non-null    object
 5   robbery_crime        439 non-null    object
 6   assault_crime        439 non-null    object
 7   property_crime       439 non-null    object
 8   burglary_crime       439 non-null    object
 9   larceny_theft        439 non-null    object
 10  motor_vehicle_theft  439 non-null    object
 11  arson                439 non-null    object
 12  longitude            439 non-null    float64
 13  latitude             439 non-null    float64
 14  average_housing_age  439 non-null    float64
 15  total_rooms          439 non-null    float64
 16  total_bedrooms       439 non-null    float64
 17  population_drop      439 non-null    float64
 18  total_households     439 non-null    float64
 19  average_income       439 non-null    float64
 20  average_house_value  439 non-null    float64
dtypes: float64(9), int64(1), object(11)
memory usage: 72.1+ KB

In [ ]:
cols_to_drop = ['population_drop', 'longitude', 'latitude']

merged_data = merged_data.drop(cols_to_drop, axis = 1)

merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   city                 439 non-null    object
 1   population           439 non-null    object
 2   violent_crime        439 non-null    object
 3   murder               439 non-null    int64
 4   rape_cases           439 non-null    object
 5   robbery_crime        439 non-null    object
 6   assault_crime        439 non-null    object
 7   property_crime       439 non-null    object
 8   burglary_crime       439 non-null    object
 9   larceny_theft        439 non-null    object
 10  motor_vehicle_theft  439 non-null    object
 11  arson                439 non-null    object
 12  average_housing_age  439 non-null    float64
 13  total_rooms          439 non-null    float64
 14  total_bedrooms       439 non-null    float64
 15  total_households     439 non-null    float64
 16  average_income       439 non-null    float64
 17  average_house_value  439 non-null    float64
dtypes: float64(6), int64(1), object(11)
memory usage: 61.9+ KB

In [ ]:
merged_data.to_csv('property_crime_data.csv')

### Further works
* Drop some columns not needed
* Use all the data from `df` instead of sampling it.
* Go ahead and use the data to answer the conceptual questions raised.
* Create a new data from it.
* Do some analysis