In [4]:
import pandas as pd
import seaborn as sns
import numpy as np

In [5]:
#df = pd.read_csv("housing.csv")

In [6]:
#df

In [7]:
"""import pandas as pd
from geopy.geocoders import Nominatim
from geopy.point import Point

# Initialize Nominatim API
geolocator = Nominatim(user_agent="test")

def reverse_geocoding(lat, lon):
    try:
        location = geolocator.reverse(Point(lat, lon))
        print(location)
        return location.raw['display_name']
    except:
        return None


# Apply reverse geocoding
df['address'] = np.vectorize(reverse_geocoding)(df['latitude'], df['longitude'])

print(df)"""

'import pandas as pd\nfrom geopy.geocoders import Nominatim\nfrom geopy.point import Point\n\n# Initialize Nominatim API\ngeolocator = Nominatim(user_agent="test")\n\ndef reverse_geocoding(lat, lon):\n    try:\n        location = geolocator.reverse(Point(lat, lon))\n        print(location)\n        return location.raw[\'display_name\']\n    except:\n        return None\n\n\n# Apply reverse geocoding\ndf[\'address\'] = np.vectorize(reverse_geocoding)(df[\'latitude\'], df[\'longitude\'])\n\nprint(df)'

In [8]:
#df.to_csv("new.csv")

In [9]:
import sqlalchemy as sql

In [10]:
import pandas as pd

In [11]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///db1.db')

In [12]:
df = pd.read_csv('/Users/tsovinar/Desktop/PropertyCrime/DE_Property_Crime/Data/property_crime_data.csv')
df.to_sql(name='crime_table', con=engine, if_exists='replace')

439

In [13]:
housedf = pd.read_csv('/Users/tsovinar/Desktop/PropertyCrime/DE_Property_Crime/Data/new.csv')

In [14]:
df

,Unnamed: 0,city,population,violent_crime,murder,rape_cases,robbery_crime,assault_crime,property_crime,burglary_crime,larceny_theft,motor_vehicle_theft,arson,average_housing_age,total_rooms,total_bedrooms,total_households,average_income,average_house_value
0,0,Adelanto,"33,005",212,2,14,48,148,808,434,254,120,24,10.666667,9268.0,2240.0,2004.0,1.681733,66933.333333
1,1,Agoura Hills,"20,970",15,0,1,6,8,310,82,217,11,0,8.000000,33408.0,4597.0,4397.0,6.934250,449600.500000
2,2,Alameda,"78,613",148,2,7,61,78,"1,819",228,"1,245",346,18,45.057692,131786.0,25494.0,25795.0,3.813152,247886.538462
3,3,Albany,"19,723",34,1,6,16,11,605,95,447,63,0,42.750000,32001.0,7151.0,6810.0,3.669300,220562.500000
4,4,Alhambra,"86,175",168,1,13,74,80,"1,929",305,"1,413",211,6,37.437500,117422.0,28248.0,27308.0,3.206000,217750.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,434,Yountville,"3,030",7,0,0,0,7,46,7,36,3,0,17.000000,4524.0,946.0,870.0,2.980150,188100.000000
435,435,Yreka,"7,507",47,1,4,4,38,309,85,188,36,1,29.800000,15337.0,3154.0,3011.0,2.262380,65780.000000
436,436,Yuba City,"65,974",216,0,28,66,122,"1,792",429,"1,160",203,14,23.933333,75544.0,15072.0,14441.0,2.884130,92993.333333
437,437,Yucaipa,"53,498",94,2,8,22,62,"1,309",263,838,208,12,24.421053,67846.0,13307.0,12464.0,3.034968,124742.105263
438,438,Yucca Valley,"21,672",151,0,8,30,113,664,217,381,66,8,14.285714,32324.0,6418.0,5763.0,2.718271,88557.142857

In [15]:
housedf

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,address
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,"Ecological Study Area, Smyth Road, Panoramic H..."
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,"Grizzly Peak Open Space, Fish Ranch Road, Oakl..."
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,"Grove Shafter Freeway, Upper Rockridge, Oaklan..."
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame..."
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame..."
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,"Garden Valley Road, Yuba County, California, 9..."
20636,20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,"La Porte Road, Woodleaf, Challenge, Yuba Count..."
20637,20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,"Indiana Ranch Road, Yuba County, California, 9..."
20638,20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,"Vierra Road, Yuba County, California, 95972, U..."
20639,20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,"9429, Marysville Road, Yuba County, California..."

In [16]:

housedf['city'] = ""

In [17]:
housedf

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,address,city
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,"Ecological Study Area, Smyth Road, Panoramic H...",
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,"Grizzly Peak Open Space, Fish Ranch Road, Oakl...",
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,"Grove Shafter Freeway, Upper Rockridge, Oaklan...",
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...",
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...",
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,"Garden Valley Road, Yuba County, California, 9...",
20636,20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,"La Porte Road, Woodleaf, Challenge, Yuba Count...",
20637,20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,"Indiana Ranch Road, Yuba County, California, 9...",
20638,20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,"Vierra Road, Yuba County, California, 95972, U...",
20639,20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,"9429, Marysville Road, Yuba County, California...",

In [18]:
housedf['city'] = ''
cities = df['city'].tolist()

# define a lambda function to extract the city and match it with the list of cities
match_city = lambda x: [city for city in cities if city in x]

# apply the lambda function to the 'address' column
housedf['city'] = housedf['address'].apply(match_city)

# print the resulting dataframe
print(housedf)

       Unnamed: 0  longitude  latitude  housing_median_age  total_rooms  \
0               0    -122.23     37.88                41.0        880.0
1               1    -122.22     37.86                21.0       7099.0
2               2    -122.24     37.85                52.0       1467.0
3               3    -122.25     37.85                52.0       1274.0
4               4    -122.25     37.85                52.0       1627.0
...           ...        ...       ...                 ...          ...
20635       20635    -121.09     39.48                25.0       1665.0
20636       20636    -121.21     39.49                18.0        697.0
20637       20637    -121.22     39.43                17.0       2254.0
20638       20638    -121.32     39.43                18.0       1860.0
20639       20639    -121.24     39.37                16.0       2785.0

       total_bedrooms  population  households  median_income  \
0               129.0       322.0       126.0         8.3252
1              1106.0      2401.0      1138.0         8.3014
2               190.0       496.0       177.0         7.2574
3               235.0       558.0       219.0         5.6431
4               280.0       565.0       259.0         3.8462
...               ...         ...         ...            ...
20635           374.0       845.0       330.0         1.5603
20636           150.0       356.0       114.0         2.5568
20637           485.0      1007.0       433.0         1.7000
20638           409.0       741.0       349.0         1.8672
20639           616.0      1387.0       530.0         2.3886

       median_house_value ocean_proximity  \
0                452600.0        NEAR BAY
1                358500.0        NEAR BAY
2                352100.0        NEAR BAY
3                341300.0        NEAR BAY
4                342200.0        NEAR BAY
...                   ...             ...
20635             78100.0          INLAND
20636             77100.0          INLAND
20637             92300.0          INLAND
20638             84700.0          INLAND
20639             89400.0          INLAND

                                                 address  \
0      Ecological Study Area, Smyth Road, Panoramic H...
1      Grizzly Peak Open Space, Fish Ranch Road, Oakl...
2      Grove Shafter Freeway, Upper Rockridge, Oaklan...
3      6365, Florio Street, Rockridge, Oakland, Alame...
4      6365, Florio Street, Rockridge, Oakland, Alame...
...                                                  ...
20635  Garden Valley Road, Yuba County, California, 9...
20636  La Porte Road, Woodleaf, Challenge, Yuba Count...
20637  Indiana Ranch Road, Yuba County, California, 9...
20638  Vierra Road, Yuba County, California, 95972, U...
20639  9429, Marysville Road, Yuba County, California...

                              city
0              [Alameda, Berkeley]
1               [Alameda, Oakland]
2      [Alameda, Oakland, Shafter]
3               [Alameda, Oakland]
4               [Alameda, Oakland]
...                            ...
20635                           []
20636                           []
20637                           []
20638                           []
20639                 [Marysville]

[20640 rows x 13 columns]

In [19]:
housedf

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,address,city
0,0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,"Ecological Study Area, Smyth Road, Panoramic H...","[Alameda, Berkeley]"
1,1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,"Grizzly Peak Open Space, Fish Ranch Road, Oakl...","[Alameda, Oakland]"
2,2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,"Grove Shafter Freeway, Upper Rockridge, Oaklan...","[Alameda, Oakland, Shafter]"
3,3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...","[Alameda, Oakland]"
4,4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,"6365, Florio Street, Rockridge, Oakland, Alame...","[Alameda, Oakland]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,"Garden Valley Road, Yuba County, California, 9...",[]
20636,20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,"La Porte Road, Woodleaf, Challenge, Yuba Count...",[]
20637,20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,"Indiana Ranch Road, Yuba County, California, 9...",[]
20638,20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,"Vierra Road, Yuba County, California, 95972, U...",[]
20639,20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,"9429, Marysville Road, Yuba County, California...",[Marysville]

In [20]:
housedf.to_csv('housingwcities.csv')

In [21]:
#reprrocessing
# extract the second element of the column
housedf['guessed_city'] = df['city'].str.split(",").str[1]

In [22]:
#housedf.to_sql(name='property_table_one', con=engine, if_exists='replace')

In [23]:
len(housedf)

20640